version: 2
updates:
  # Monitoramento de dependências do Back-end (Python/pip)
  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10

  # Monitoramento de dependências do Front-end (Node.js/npm)
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10

  # Monitoramento de dependências das GitHub Actions (CI/CD)
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
