"""refactor: restructure models and add enums to support RBAC

Revision ID: c16bd31abcb4
Revises:
Create Date: 2026-10-06 14:42:17.554515

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c16bd31abcb4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pessoas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('matricula', sa.String(), nullable=False),
    sa.Column('tipo_vinculo', sa.Enum('ALUNO', 'PROFESSOR', 'SERVIDOR', 'COORDENACAO', name='tipovinculo', native_enum=False), nullable=False),
    sa.Column('modalidade', sa.Enum('INTEGRADO', 'SUBSEQUENTE', 'SUPERIOR', name='modalidadeensino', native_enum=False), nullable=True),
    sa.Column('is_interno', sa.Boolean(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('foto_url', sa.String(), nullable=True),
    sa.Column('qr_code_hash', sa.String(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pessoas_email'), 'pessoas', ['email'], unique=True)
    op.create_index(op.f('ix_pessoas_id'), 'pessoas', ['id'], unique=False)
    op.create_index(op.f('ix_pessoas_matricula'), 'pessoas', ['matricula'], unique=True)
    op.create_index(op.f('ix_pessoas_qr_code_hash'), 'pessoas', ['qr_code_hash'], unique=True)
    op.create_table('movimentacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pessoa_id', sa.Integer(), nullable=False),
    sa.Column('operador_id', sa.Integer(), nullable=False),
    sa.Column('local_acesso', sa.Enum('PORTARIA', 'REFEITORIO', name='localacesso', native_enum=False), nullable=False),
    sa.Column('tipo', sa.Enum('ENTRADA', 'SAIDA', name='sentidomovimentacao', native_enum=False), nullable=False),
    sa.Column('data_hora', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['operador_id'], ['usuarios_sistema.id'], ),
    sa.ForeignKeyConstraint(['pessoa_id'], ['pessoas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movimentacoes_id'), 'movimentacoes', ['id'], unique=False)
    op.drop_index(op.f('ix_movimentacoes_portaria_id'), table_name='movimentacoes_portaria')
    op.drop_table('movimentacoes_portaria')
    op.drop_index(op.f('ix_alunos_email'), table_name='alunos')
    op.drop_index(op.f('ix_alunos_id'), table_name='alunos')
    op.drop_index(op.f('ix_alunos_matricula'), table_name='alunos')
    op.drop_index(op.f('ix_alunos_qr_code_hash'), table_name='alunos')
    op.drop_table('alunos')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alunos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('matricula', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('nome_completo', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('curso', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('modalidade', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('idade', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('foto_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('qr_code_hash', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_interno', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('status', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('alunos_pkey'))
    )
    op.create_index(op.f('ix_alunos_qr_code_hash'), 'alunos', ['qr_code_hash'], unique=True)
    op.create_index(op.f('ix_alunos_matricula'), 'alunos', ['matricula'], unique=True)
    op.create_index(op.f('ix_alunos_id'), 'alunos', ['id'], unique=False)
    op.create_index(op.f('ix_alunos_email'), 'alunos', ['email'], unique=True)
    op.create_table('movimentacoes_portaria',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('aluno_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tipo', sa.VARCHAR(length=7), autoincrement=False, nullable=False),
    sa.Column('data_hora', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], name=op.f('movimentacoes_portaria_aluno_id_fkey')),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios_sistema.id'], name=op.f('movimentacoes_portaria_usuario_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('movimentacoes_portaria_pkey'))
    )
    op.create_index(op.f('ix_movimentacoes_portaria_id'), 'movimentacoes_portaria', ['id'], unique=False)
    op.drop_index(op.f('ix_movimentacoes_id'), table_name='movimentacoes')
    op.drop_table('movimentacoes')
    op.drop_index(op.f('ix_pessoas_qr_code_hash'), table_name='pessoas')
    op.drop_index(op.f('ix_pessoas_matricula'), table_name='pessoas')
    op.drop_index(op.f('ix_pessoas_id'), table_name='pessoas')
    op.drop_index(op.f('ix_pessoas_email'), table_name='pessoas')
    op.drop_table('pessoas')
    # ### end Alembic commands ###
